# Generated by Django 6.0 on 2026-01-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedroute',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
