# Generated by Django 6.0 on 2026-01-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='google_product_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='apple_product_id',
        ),
    ]
