# Generated by Django 6.0 on 2026-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.IntegerField(default=7, help_text='Trial period in days'),
        ),
    ]
